#!/bin/bash
echo "Quick Test Instructions:"
echo ""
echo "1. Open Chrome/Edge and go to: chrome://extensions/ (or edge://extensions/)"
echo "2. Enable 'Developer mode' (toggle in top-right)"
echo "3. Click 'Load unpacked'"
echo "4. Select this directory: $(pwd)"
echo ""
echo "Note: You may see a warning about missing icons - that's OK for testing!"
echo ""
echo "5. Go to https://chatgpt.com and select some text"
echo "6. Look for the green 'Collected (n)' button in bottom-right"
echo ""
echo "For detailed testing, see TESTING.md"
